language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
node_js: "10"
jobs:
  include:
    - stage: Shrinkwrap
      node_js: 10
      before_script: 
    - stage: Tests + Shrinkwrap
      os:
        - linux
        - sudo: false
      script: npm run test && npm run e2e-test
      node_js: "11"
    - stage:
      os:
        - linux
        - sudo: false
      script: npm run test && npm run e2e-test
      node_js: "10"
      before_install: npm install -g greenkeeper-lockfile
      install: npm install
      before_script: greenkeeper-lockfile-update
      script: npm run test && npm run e2e-test
      after_script: greenkeeper-lockfile-update
    - stage:
      os:
        - linux
        - sudo: false
      script: npm run test && npm run e2e-test
      node_js: "8"
    - stage:
      os:
        - linux
        - sudo: false
      env:
        # this is just to indicate in the Travis job list that this is generating docs
        - GENERATE_DOCS=true
      script: npm run generate-docs
    - stage: BinTray Bundle Build and Upload
      # only want to run this on the main master branch
      if: branch = master AND type != pull_request
      os:
        - osx
        - osx_image: xcode9.4
      env:
        - NODE_ENV=production
        - CC=gcc
        - CXX=g++
      before_install:
        - gcc --version
      install:
        # Install prod dependencies
        - npm install

        # Install only the dev dependencies that we need
        - npm install --only=dev gulp
        - npm install --only=dev appium-gulp-plugins
      before_script:
        # Build the assets
        - npm run build

        # Remove the dev depenedencies
        - npm prune
      script: npm run zip-and-upload
