language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
node_js: "10"
jobs:
  include:
    # Run the tests and generate/update npm-shrinkwrap.json
    - stage: Tests and Shrinkwrap
      os:
        - linux
        - sudo: false
      script: npm run test && npm run e2e-test
      node_js: "11"
    - stage:
      os:
        - linux
        - sudo: false
      script: npm run test && npm run e2e-test
      node_js: "10"
      before_install: 
        - npm install -g greenkeeper-lockfile
        - bash ./bin/has-code-changes.sh || travis_terminate 0 # If only .md files were changed, exit
      install: npm install
      before_script: greenkeeper-lockfile-update
      script: npm run test && npm run e2e-test
      after_script: greenkeeper-lockfile-update

    # Run tests in Node versions
    - stage: Test other Node versions
      os:
        - linux
        - sudo: false
      script: npm run test && npm run e2e-test
      node_js: "8"

    - stage:
      os:
        - linux
        - sudo: false
      env:
        # this is just to indicate in the Travis job list that this is generating docs
        - GENERATE_DOCS=true
      script: npm run generate-docs

    
    - stage: Bundle zip and publish beta
      # only want to run this on the main master branch
      # if: branch = master AND type != pull_request # TODO: DO NOT COMMIT THIS COMMENTED OUT! THIS NEEDS TO PUT BACK BEFORE MERGING TO MASTER!
      os:
        - osx
        - osx_image: xcode9.4
      env:
        - NODE_ENV=production
        - CC=gcc
        - CXX=g++
      before_install:
        - gcc --version
      install:
        # Install prod dependencies
        - npm install

        # Install only the dev dependencies that we need
        - npm install --only=dev gulp
        - npm install --only=dev appium-gulp-plugins
      before_script:
        # Build the assets
        - npm run build

        # Remove the dev depenedencies
        - npm prune
      script: 
        - npm run zip-and-upload
        - npm run release-beta
